name: Docker Image CI PULL REQUEST Kotlin

on:
  pull_request:
    branches: [ master ]
    paths: 'kotlin/**'

jobs:

  build-kotlin:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Kotlin runtime Docker image
      run: cd kotlin; docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/unimatrix-zero-kotlin:duck .
    - name: Push the tagged Kotlin runtime Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/unimatrix-zero-kotlin:duck