name: Docker Image CI PULL REQUEST JavaScript

on:
  pull_request:
    branches: [ master ]
    paths: 'javascript/**'

jobs:

  build-javascript:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Javascript runtime Docker image
      run: cd javascript; docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/unimatrix-zero-javascript:duck .
    - name: Push the tagged Javascript runtime Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/unimatrix-zero-javascript:duck
